version: '3'
services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
  fastapi:
    build: .
    command: uvicorn fastapi_app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
